"""Compare two iterations of the opponent model.

Iteration 1 was generated by players who assume the other side throws at random;
iteration 2 by players who best-respond to iteration 1. If the tables have
stopped moving, the process has converged and further iterations are pointless.
"""
import os, sys, random
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import cribbage as C
import opponent_model as v2
import opponent_model_v1 as v1

PAIRS = [('PONE_POLICY', 'thrown into your crib by the pone'),
         ('DEALER_POLICY', 'thrown into their own crib by the dealer'),
         ('PONE_NAIVE', 'naive pone (control -- should not move)'),
         ('DEALER_NAIVE', 'naive dealer (control -- should not move)')]


def total_variation(a, b):
    """Half the summed absolute difference: the largest probability shift."""
    classes = set(a) | set(b)
    return sum(abs(a.get(c, 0.0) - b.get(c, 0.0)) for c in classes) / 2


print("how far each table moved between iterations")
print("(total variation distance -- 0.0 is identical, 1.0 is disjoint)\n")
for name, note in PAIRS:
    old = C._expand(getattr(v1, name))
    new = C._expand(getattr(v2, name))
    shifts = sorted(((new.get(c, 0) - old.get(c, 0), c) for c in set(old) | set(new)),
                    key=lambda item: -abs(item[0]))
    biggest = ', '.join(
        f"{C._RANK_NAMES[c[0]]}-{C._RANK_NAMES[c[1]]}{'s' if c[2] else ''} {d:+.4f}"
        for d, c in shifts[:3])
    print(f"  {name:<14} {total_variation(old, new):.4f}   {note}")
    print(f"  {'':<14} biggest moves: {biggest}")

print("\neffect on pricing and decisions, over 400 random deals")
print("(v1 supplied as a custom dict, v2 as the installed \"policy\" model)\n")
random.seed(9001)
for is_dealer, label, table in [(True, "your crib  (you deal)", 'PONE_POLICY'),
                                (False, "their crib (they deal)", 'DEALER_POLICY')]:
    old_weights = C._expand(getattr(v1, table))
    crib_shift = []
    uniform_shift = []
    same = 0
    for _ in range(400):
        deal = random.sample(C._DECK, 6)
        first = C.evaluate_discards(deal, is_dealer, True, old_weights)
        second = C.evaluate_discards(deal, is_dealer, True, "policy")
        plain = C.evaluate_discards(deal, is_dealer, True)
        by_toss = {tuple(sorted(r.discard)): r.crib_ev for r in first}
        flat = {tuple(sorted(r.discard)): r.crib_ev for r in plain}
        crib_shift += [r.crib_ev - by_toss[tuple(sorted(r.discard))] for r in second]
        uniform_shift += [r.crib_ev - flat[tuple(sorted(r.discard))] for r in second]
        same += first[0].keep == second[0].keep
    print(f"  {label}")
    print(f"    crib EV, iteration 1 -> 2 : {sum(crib_shift) / len(crib_shift):+.3f} points")
    print(f"    crib EV, uniform -> 2     : {sum(uniform_shift) / len(uniform_shift):+.3f} points")
    print(f"    same discard chosen       : {same / 400:.1%} of deals")
