"""Generate opponent_model.py: what a policy opponent actually throws to the crib.

Samples random 6-card hands, runs the discard evaluator on each, and tallies the
resulting throws by (low rank, high rank, suited) -- the only properties of a
throw that affect how the crib scores, once suit symmetry is taken into account.
"""
import sys, random, time
from collections import Counter
from itertools import combinations
from multiprocessing import Pool

import os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import cribbage as C

SAMPLES = 50000
SMOOTHING = 0.01   # mix in this much uniform, so nothing is called impossible

# How many concrete two-card throws each class has in a full deck.
CLASS_SIZE = {}
for low in range(1, 14):
    for high in range(low, 14):
        if low == high:
            CLASS_SIZE[(low, high, False)] = 6      # C(4,2) same-rank pairs
        else:
            CLASS_SIZE[(low, high, True)] = 4       # one per suit
            CLASS_SIZE[(low, high, False)] = 12     # 4*4 minus the suited ones
assert sum(CLASS_SIZE.values()) == 1326


def toss_class(card_a, card_b):
    (rank_a, suit_a), (rank_b, suit_b) = card_a, card_b
    low, high = (rank_a, rank_b) if rank_a <= rank_b else (rank_b, rank_a)
    return low, high, suit_a == suit_b


def throw(job):
    hand, is_dealer, include_crib = job
    best = C.evaluate_discards(hand, is_dealer=is_dealer, include_crib=include_crib)[0]
    return toss_class(*best.discard)


def distribution(classes):
    counts = Counter(classes)
    total = sum(counts.values())
    table = {}
    for cls, size in CLASS_SIZE.items():
        empirical = counts.get(cls, 0) / total
        uniform = size / 1326
        table[cls] = (1 - SMOOTHING) * empirical + SMOOTHING * uniform
    scale = sum(table.values())
    return {cls: p / scale for cls, p in table.items()}


def emit(name, table, out, note):
    out.write(f'\n# {note}\n{name} = {{\n')
    for low in range(1, 14):
        for high in range(low, 14):
            if low == high:
                out.write(f'    ({low}, {high}): ({table[(low, high, False)]:.6f}, 0.0),\n')
            else:
                out.write(f'    ({low}, {high}): ({table[(low, high, False)]:.6f}, '
                          f'{table[(low, high, True)]:.6f}),\n')
    out.write('}\n')


if __name__ == '__main__':
    random.seed(31415)
    t0 = time.time()
    hands = [random.sample(C._DECK, 6) for _ in range(SAMPLES)]

    with Pool() as pool:
        jobs = {
            'PONE_POLICY': (False, True),
            'DEALER_POLICY': (True, True),
            'PONE_NAIVE': (False, False),
            'DEALER_NAIVE': (True, False),
        }
        tables = {}
        for name, (is_dealer, include_crib) in jobs.items():
            tables[name] = distribution(
                pool.map(throw, [(h, is_dealer, include_crib) for h in hands], 16))
            print(f'{name} done at {time.time() - t0:.0f}s', flush=True)

    with open(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'opponent_model.py'), 'w') as out:
        out.write(f'''"""What an opponent actually throws to the crib, measured rather than assumed.

cribbage._crib_ev models the opponent's two crib cards as a uniform draw from
the unseen cards. Real opponents choose: as dealer they feed their own crib, as
pone they starve yours. These tables are the empirical distribution of what they
throw, for pricing a crib against a thinking opponent instead of a random one.

Each table maps (low rank, high rank) -> (probability unsuited, probability
suited); ranks run 1 (ace) to 13 (king). Those are the only properties of a
throw that change how the crib scores, once suit symmetry is accounted for.

Generated by tools/gen_opponent_model.py from {SAMPLES:,} random 6-card hands per
table, each resolved with cribbage.evaluate_discards. POLICY opponents weigh the
crib when discarding; NAIVE ones keep their best hand and ignore the crib, which
is a useful lower bound on how much opponent skill matters. Every table is
mixed with {SMOOTHING:.0%} of the uniform distribution, so no throw is priced as
impossible just because it went unsampled.
"""
''')
        emit('PONE_POLICY', tables['PONE_POLICY'], out,
             'Thrown into YOUR crib by a pone who is trying to starve it.')
        emit('DEALER_POLICY', tables['DEALER_POLICY'], out,
             'Thrown into THEIR OWN crib by a dealer who is trying to feed it.')
        emit('PONE_NAIVE', tables['PONE_NAIVE'], out,
             'Thrown into YOUR crib by a pone who ignores the crib entirely.')
        emit('DEALER_NAIVE', tables['DEALER_NAIVE'], out,
             'Thrown into THEIR OWN crib by a dealer who ignores the crib entirely.')

    print(f'wrote /home/lance/src/cribbage/opponent_model.py in {time.time() - t0:.0f}s')
